### ISSUE TITLE
composer安装出错

### ISSUE THREAD

**Issue by xiaoguo0426** [imdgr/php-nohup#2]
你好，我想请问下，这个安装出错是什么问题？
![tim 20170726134947](https://user-images.githubusercontent.com/8944962/28606373-588f3cd6-7209-11e7-9fe4-1c2f0e1d3e31.png)

另外，文档上安装的命令少了s

**Comment by imdgr** [comment]
谢谢提醒，你的 composer.json 可以看一下吗，我刚刚试了一下，安装很顺利

**Comment by xiaoguo0426** [comment]
我是直接在github clone下来的，在目录执行composer命令、
![tim 20170727115604](https://user-images.githubusercontent.com/8944962/28653895-d0b51afa-72c2-11e7-9841-c8b0e9df1401.png)
![tim 20170727115722](https://user-images.githubusercontent.com/8944962/28653902-da8a3326-72c2-11e7-8de0-5952ad573f48.png)

**Comment by imdgr** [comment]
这个是包，不能直接这么用
你新建一个目录，执行 composer init
然后再执行 composer require dgr/nohup

**Comment by imdgr** [comment]
建议你看看 composer 文档
